### ISSUE TITLE
Some feats like Hardy, need a bit of update.

### ISSUE THREAD

**Issue by Fran89** [TikaelSol/hopefinder#2]
I'm not entirely sure but some feats other than Hardy might need updates Bulk 3 instead of bulk 2, plus a bit of description is missing. Adding to this the Survivor class is a bit broken after the prompts 1 of the free boost is broken. 

I can try to fork and see if I can fix it, but I haven't tried to modify modules for Foundry yet. I'll see if there's anything else.

**Comment by TikaelSol** [comment]
Found the issue with the fourth boost, it does work if you take a flaw which is why I didn't catch it. As for the hardy issue... hardy doesn't add to your bulk limit.

>You can take a beating. Increase your Fortitude proficiency by 1 step. Increase your hit points by 4.

Right below that is Hauler which does increase your bulk limit by 3 and it is working correctly.
